name: rearticle_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.5.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.8
  fl_chart: ^0.66.0
  image_picker: ^1.0.7
  permission_handler: ^11.3.0
  intl: ^0.20.2
  in_app_purchase: ^3.1.13
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0
  path: ^1.9.1
  path_provider: ^2.1.2
  file_picker: ^8.0.0
  phosphor_flutter: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true